services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: on-failure:5
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: on-failure:5
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    restart: on-failure:5
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  redis:
    image: redis:latest
    env_file:
      - ./.env
    restart: on-failure:5
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    restart: on-failure:5

volumes:
  postgres_data:
