export enum Errors {
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_TOKEN = 'INVALID_TOKEN',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  INVALID_REQUEST = 'INVALID_REQUEST',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  NO_FUNDS = 'NO_FUNDS',
  NOT_FOUND = 'USER_NOT_FOUND',
}

export const IS_PUBLIC_KEY = '_isPublic';
export const REDIS_CLIENT = 'REDIS_CLIENT';
